<?xml version="1.0"?>
<package format="3">
  <name>lasr_tf</name>
  <version>0.0.0</version>
  <description>The lasr_tf package</description>
  <maintainer email="fadimostefai@gmail.com">fadi</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>lasr_helper_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
