#!/usr/bin/env python3
import os
from pathlib import Path

WHISPER_CACHE = os.path.join(str(Path.home()), '.cache', 'whisper')
os.makedirs(WHISPER_CACHE, exist_ok=True)
os.environ["TIKTOKEN_CACHE_DIR"] = WHISPER_CACHE

import sys

if len(sys.argv) < 3:
    print('Usage:')
    print('rosrun lasr_speech_recognition transcribe_microphone by-index <device_index>')
    print('rosrun lasr_speech_recognition transcribe_microphone by-name <substring>')
    exit(1)
else:
    matcher = sys.argv[1]
    device_index = None
    if matcher == 'by-index':
        device_index = int(sys.argv[2])
    elif matcher == 'by-name':
        import speech_recognition as sr
        microphones = enumerate(sr.Microphone.list_microphone_names())

        target_name = ' '.join(sys.argv[2:])
        for index, name in microphones:
            if target_name in name:
                device_index = index
                break
        
        if device_index is None:
            print('Could not find device!')
            exit(1)
    else:
        print('Invalid matcher')
        exit(1)

import rospy
from std_srvs.srv import Empty, EmptyResponse
rospy.init_node('transcribe_mic', anonymous=True)

from lasr_speech_recognition_whisper import SpeechRecognitionToTopic, MicrophonePhraseCollector
worker = SpeechRecognitionToTopic(MicrophonePhraseCollector(device_index=device_index), "base.en", "transcription", infer_partial = False, run_inference = False)

def start_listening(_):
    worker.start_listening()
    return EmptyResponse()
def stop_listening(_):
    worker.stop_listening()
    return EmptyResponse()

rospy.Service('/whisper/start_listening', Empty, start_listening)
rospy.Service('/whisper/stop_listening', Empty, stop_listening)

worker.start()
