<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lasr_sentence_embedding</name>
  <version>0.0.0</version>
  <description>The sentence embedding package</description>
  <maintainer email="yara.alkhelaiwi@kcl.ac.uk">Yara</maintainer>
  <license>MIT</license>

  <depend>lasr_llm_interfaces</depend>
  <depend>rclpy</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
