#!/usr/bin/env python3
import rospy
import actionlib
from unsafe_traversal.msg import AlignToGoalAction, AlignToGoalGoal

# initialise node
rospy.init_node('test_align_action', anonymous=True)

# setup action client
align_to_goal_client = actionlib.SimpleActionClient(
    '/unsafe_traversal/align_to_goal', AlignToGoalAction)
align_to_goal_client.wait_for_server()

start = (4.3, 1.3)
end = (1.3, 1.05)

goal = AlignToGoalGoal()

# start pose
goal.start_pose.header.stamp = rospy.get_rostime()
goal.start_pose.header.frame_id = 'map'

goal.start_pose.pose.position.x = start[0]
goal.start_pose.pose.position.y = start[1]
goal.start_pose.pose.position.z = 0

# end pose
goal.end_pose.header.stamp = rospy.get_rostime()
goal.end_pose.header.frame_id = 'map'

goal.end_pose.pose.position.x = end[0]
goal.end_pose.pose.position.y = end[1]
goal.end_pose.pose.position.z = 0

# send goal
align_to_goal_client.send_goal(goal)
align_to_goal_client.wait_for_result()
