#!/usr/bin/env python3
import rospy
from unsafe_traversal.srv import ChangeTraversalParameters

# initialise node
rospy.init_node('test_service', anonymous=True)

# prepare service proxy
set_unsafe = rospy.ServiceProxy(
    '/unsafe_traversal/set_unsafe_traversal', ChangeTraversalParameters)

input("Press enter to switch to unsafe.")
set_unsafe(True)

input("Press enter to switch to safe.")
set_unsafe(False)
