string object_id # name of object in the planning scene
string mesh_name # filename belonging to the meshes
geometry_msgs/TransformStamped transform # transform produced by registration
---
bool success
---