# Request
# Image to run inference on
sensor_msgs/Image image_raw

# BodyPix model to use
string dataset

# How certain the detection should be to include
float32 confidence

# Whether to return keypoints that are out of bound
bool keep_out_of_bounds
---
# Response
# keypoints
lasr_vision_interfaces/BodyPixKeypoint[] keypoints

# keypoints
lasr_vision_interfaces/BodyPixKeypointNormalized[] normalized_keypoints