# 2D methods are "centered", "left-most" "right-most" "top-most" "bottom-most"
# 3D methods are "closest" "furthest"
string method

# Whether to turn all pixels other than the YOLo mask to black
# If false, uses bounding-box cropping.
bool use_mask

# Name of the objects to get
string[] object_names

# Name of the yolo model to use for detections. If using mask is True,
# this must be a valid segementation model.
string yolo_model

# Confidence for YOLO model detections.
float32 yolo_model_confidence

# NMS threshold for YOLO model detections
float32 yolo_nms_threshold

---
# The combined masked image, if use_mask is True, else empty.
sensor_msgs/Image masked_img

# A list of all the cropped images of detections sorted according to the
# given method.
sensor_msgs/Image[] cropped_imgs

# A list of 2D detections, sorted to match the cropped_imgsa
lasr_vision_msgs/Detection[] detections_2d

# A list of 3D detections, sorted to match the cropped_imgs
lasr_vision_msgs/Detection3D[] detections_3d