# Image to run inference on 
sensor_msgs/Image image_raw

# Maximum confidence for detection to be returned
float32 confidence_threshold

# List of queries to detect
string[] queries

# List of query mappings; must be same length as queries. e.g., "orange carton" in query could get mapped to "orange juice" which would be name in what the detection returns
string[] query_mappings

---
# Detection result. Detectopm names will be as defined in query_mappings NOT queries
lasr_vision_msgs/Detection[] detected_objects

