# Image to run inference on
sensor_msgs/Image image_raw

uint8[] head_mask_data  # For serialized array data
uint32[] head_mask_shape  # To store the shape of the array
string head_mask_dtype  # Data type of the array elements

uint8[] torso_mask_data
uint32[] torso_mask_shape
string torso_mask_dtype
---

# Detection result
string description
