# Image to run inference on
sensor_msgs/Image image_raw

# Depth image
sensor_msgs/Image depth_image

# Camera info for depth camera
# we may want to keep this hardcoded in future
# it shouldn't change, unless we recalibrate the depth camera
sensor_msgs/CameraInfo depth_camera_info

# YOLO model to use
string model

# Confidence threshold
float32 confidence

# Classes to filter, i.e. only detect these classes
string[] filter

# target frame for 3D estimate
string target_frame
---
# Detection result
lasr_vision_msgs/Detection3D[] detected_objects