<?xml version="1.0"?>
<package format="3">
  <name>open_vocabulary_models</name>
  <version>0.1.0</version>
  <description>Service wrapper for open-vocabulary models</description>
  <maintainer email="brienza@diag.uniroma1.it">Michele Brienza</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>lasr_vision_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
