<?xml version="1.0"?>
<package format="3">
  <name>manipulation_actions</name>
  <version>0.1.0</version>
  <description>Grasping pipeline: PlayMotion2 pregrasp + arm_1_joint sweep + approach</description>
  <maintainer email="brienza@diag.uniroma1.it">Michele Brienza</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>control_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>pymoveit2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
