<?xml version="1.0"?>
<package format="3">
  <name>lasr_vision_lang_sam</name>
  <version>0.0.1</version>
  <description>LangSAM service node</description>

  <maintainer email="matthew.s.barker@kcl.ac.uk">Matt Barker</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <exec_depend>lasr_vision_interfaces</exec_depend>
  <exec_depend>lasr_tf</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>