name: Bug Report
description: Report issues/bugs found.
title: "[Bug]: "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug! Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Description of the Bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we recreate this issue?
      placeholder: |
        - Run ...
        - See [...] package. Line/ method [...]
        - See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What is the expected output?
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Info
      description: Additional Information. If applicable, drag and drop screenshots or paste log outputs here.