play_motion:
  motions:
    higher_3:
      joints: [torso_lift_joint]
      points:
      - positions: [0.30]
        time_from_start: 0.0
    higher_2:
      joints: [torso_lift_joint]
      points:
      - positions: [0.26]
        time_from_start: 0.0
    higher_1:
      joints: [torso_lift_joint]
      points:
      - positions: [0.24]
        time_from_start: 0.0
    middle:
      joints: [torso_lift_joint]
      points:
      - positions: [0.22]
        time_from_start: 0.0 
    lower_1:
      joints: [torso_lift_joint]
      points:
      - positions: [0.20]
        time_from_start: 0.0
    lower_2:
      joints: [torso_lift_joint]
      points:
      - positions: [0.18]
        time_from_start: 0.0
    lower_3:
      joints: [torso_lift_joint]
      points:
      - positions: [0.16]
        time_from_start: 0.0
    