arena:
  polygon: [[1.0, 0.0], [1.0, 1.0], [0.0, 1.0], [0.0, 0.0]] # Vertices composing the polygon of the arena
  rooms: # Rooms in the arena
    bedroom: # Room name
      pose: # Fixed pose in the room, will be used for navigating to the room 
        position: {x: 0.0, y: 0.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
      polygon: [[0.0, 0.0], [0.0, 1.0], [1.0, 1.0], [1.0, 0.0]] # Vertices composing the polygon of the room
      beacons: # Beacons in the room
        bed: # Beacon name
          near_pose: # Fixed pose in the room, will be used for navigating to the beacon
            position: {x: 0.5, y: 0.5, z: 0.0}
            orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
          near_polygon:  [[0.4, 0.4], [0.4, 0.6], [0.6, 0.6], [0.6, 0.4]]
          search_pose: # Pose to search for the beacon for objects
            position: {x: 0.5, y: 0.5, z: 0.0}
            orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
          search_polygon: [[0.4, 0.4], [0.4, 0.6], [0.6, 0.6], [0.6, 0.4]] # Vertices composing the polygon of the beacon, for search
    kitchen:
      pose:
        orientation: {}
        position: {}
      polygon:
      beacons:
    office:
      pose:
        orientation: {}
        position: {}
      polygon:
      beacons:
    living_room:
      pose:
        orientation: {}
        position: {}
      polygon:
      beacons:
