objects:
  # --- fabric (laundry table in laundry) ---
  white_shirt:
    category: fabric
    location: laundry table
    grabbable: true
    size: small
    aliases: []

  grey_shirt:
    category: fabric
    location: laundry table
    grabbable: true
    size: small
    aliases: []

  blue_shirt:
    category: fabric
    location: laundry table
    grabbable: true
    size: small
    aliases: []

  black_shirt:
    category: fabric
    location: laundry table
    grabbable: true
    size: small
    aliases: []
  
  hand_towel:
    category: fabric
    location: laundry table
    grabbable: true
    size: small
    aliases: []

  # --- toy (bed in bedroom) ---
  rubiks_cube:
    category: fabric
    location: bed
    grabbable: true
    size: small
    aliases: [cube, rubiks]

  # --- snack (shelf in laundry) ---
  pringles:
    category: snack
    location: shelf
    grabbable: true
    size: small
    aliases: []
  seaweed:
    category: snack
    location: shelf
    grabbable: true
    size: small
    aliases: []

  # --- fruit (dinner table in kitchen) ---
  apple:
    category: fruit
    location: dinner table
    grabbable: true
    size: small
    aliases: []
  peach:
    category: fruit
    location: dinner table
    grabbable: true
    size: small
    aliases: []
  mangostane:
    category: fruit
    location: dinner table
    grabbable: true
    size: small
    aliases: []
  lemon:
    category: fruit
    location: dinner table
    grabbable: true
    size: small
    aliases: []
  yellow_bellpepper:
    category: fruit
    location: dinner table
    grabbable: true
    size: small
    aliases: []
  red_bellpepper:
    category: fruit
    location: dinner table
    grabbable: true
    size: small
    aliases: []

  # --- food (coffee table in living room) ---
  instant_noodles:
    category: food
    location: coffee table 
    grabbable: true
    size: small
    aliases: []
  cornflakes:
    category: food
    location: coffee table 
    grabbable: true
    size: small
    aliases: []

  # --- drinks (cabinet in kitchen) ---
  coke:
    category: drink
    location: cabinet     # Sub-location
    grabbable: true
    size: small
    aliases: [coke, soda]
  red_bull:
    category: drink
    location: cabinet
    grabbable: true
    size: small
    aliases: []
  milk:
    category: drink
    location: cabinet
    grabbable: true
    size: small
    aliases: [oj]
  soju:
    category: drink
    location: cabinet
    grabbable: true
    size: small
    aliases: []
  pepsi:
    category: drink
    location: cabinet
    grabbable: true
    size: small
    aliases: []

  # --- cleaning supplies (counter in Kitchen) ---
  dishwasher_tab:
    category: cleaning supply
    location: laundry table
    grabbable: true
    size: small
    aliases: []
  sponge:
    category: cleaning supply
    location: laundry table
    grabbable: true
    size: small
    aliases: []
  sponge:
    category: cleaning supply
    location: laundry table
    grabbable: true
    size: small
    aliases: []

  # --- dishes (kitchen table) ---
  cup:
    category: dish
    location: dishwasher
    grabbable: true
    size: small
    aliases: []
  spoon:
    category: dish
    location: dishwasher
    grabbable: true
    size: small
    aliases: []
  plate:
    category: dish
    location: dishwasher
    grabbable: true
    size: small
    aliases: []
  knife:
    category: dish
    location: dishwasher
    grabbable: true
    size: small
    aliases: []
  fork:
    category: dish
    location: dishwasher
    grabbable: true
    size: small
    aliases: []
  bowl:
    category: dish
    location: dishwasher
    grabbable: true
    size: small
    aliases: