min_height: 0.40
max_height: 1.2

angle_min      : !degrees -180.0
angle_max      : !degrees  180.0
angle_increment: !degrees  1
scan_time: 0.25 # 6Hz

range_min: 0.30
range_max: 100.0

target_frame: base_footprint

use_concurrency: 8  # use two parallel threads
use_inf        : true  # if false the costmap doesn't get cleaned (?)

transform_tolerance: 0.1
