min_height: 0.05
max_height: 2.0

angle_min      : !degrees -10.0
angle_max      : !degrees  10.0
angle_increment: !degrees  0.3333
scan_time: 0.166 # 6Hz

range_min: 0.25
range_max: 1.2

target_frame: base_footprint

use_concurrency: 8  # use two parallel threads
use_inf        : false

transform_tolerance: 0.02