#!/usr/bin/env python3
import rospkg
import os

r = rospkg.RosPack()
os.chdir(os.path.join(r.get_path('coffee_shop_ui'), 'robot-interface'))

if not os.path.exists('.next/BUILD_ID'):
    print('Run `rosrun coffee_shop_ui build` first!')
    exit(1)

import subprocess
subprocess.call("npm run start", shell=True)
