#!/usr/bin/env python3

import rospy
import actionlib

from pal_interaction_msgs.msg import TtsGoal, TtsAction

class TtsNode:
    def __init__(self):
        self._server = actionlib.SimpleActionServer('/tts', TtsAction, self.execute, False)
        self._server.start()
    
    def execute(self, goal):
        rospy.loginfo(goal)
        self._server.set_succeeded()

rospy.init_node("log_tts_events", anonymous=True)
TtsNode()
rospy.spin()
