#!/usr/bin/env python3
import sys

if len(sys.argv) < 3:
    print('Usage:')
    print('rosrun lasr_speech_recognition transcribe_microphone by-index <device_index>')
    print('rosrun lasr_speech_recognition transcribe_microphone by-name <substring>')
    exit(1)
else:
    matcher = sys.argv[1]
    device_index = None
    if matcher == 'by-index':
        device_index = int(sys.argv[2])
    elif matcher == 'by-name':
        import speech_recognition as sr
        microphones = enumerate(sr.Microphone.list_microphone_names())

        for index, name in microphones:
            if sys.argv[2] in name:
                device_index = index
                break
        
        if device_index is None:
            print('Could not find device!')
            exit(1)
    else:
        print('Invalid matcher')
        exit(1)

import rospy
rospy.init_node('transcribe_mic', anonymous=True)

from lasr_speech_recognition import SpeechRecognitionToTopic, MicrophonePhraseCollector
SpeechRecognitionToTopic(MicrophonePhraseCollector(device_index=device_index), "base.en", "transcription").start()
