#!/usr/bin/env python3
import sys

if len(sys.argv) < 2:
    print('Usage: rosrun lasr_speech_recognition transcribe_microphone <device_index>')
    exit()
else:
    device_index = int(sys.argv[1])

import rospy
rospy.init_node('transcribe_mic', anonymous=True)

from lasr_speech_recognition import SpeechRecognitionToTopic, MicrophonePhraseCollector
SpeechRecognitionToTopic(MicrophonePhraseCollector(device_index=device_index), "base.en", "transcription").start()
