/**:
  ros__parameters:
    pick_and_place:
      table:
        pose:
          position: {x: 4.65, y: 2.5, z: 0.0}
          orientation: {x: 0.0, y: 0.0, z: -0.9565, w: 0.2919}
        look_point: [5.25, 2.27, 0.75]
        polygon: [3.5, 1.0, 5.5, 1.0, 5.5, 3.5, 3.5, 3.5]
        search_polygon: [5.3, 3.8, 7.8, 3.8, 7.8, 5.9, 5.3, 5.9]
        z_min: 0.7
        z_max: 1.5
      cabinet:
        pose:
          position: {x: 0.0, y: 0.0, z: 0.0}
          orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
      objects: ["cup", "can", "bottle", "bowl", "box"]