# Used to test 

go_to_location:   # the `go_to_location` Node's Parameters
  ros__parameters:
    start_pose:
      position:
        x: -9.6
        y: 0.368
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.6909244042647134
        w: 0.7229270140141748