#!/usr/bin/env python3
import rospy

rospy.init_node("better_qualification")

from qualification.msg import (
    WaitGreetAction,
    WaitGreetGoal,
    IdentifyAction,
    IdentifyGoal,
    GreetAction,
    GreetGoal,
    GetNameAction,
    GetNameGoal,
    LearnFaceAction,
    LearnFaceGoal,
    GetCommandAction,
    GetCommandGoal,
)

from actionlib import SimpleActionClient


wait_greet = SimpleActionClient("wait_greet", WaitGreetAction)
wait_greet.wait_for_server()

identify = SimpleActionClient("identify", IdentifyAction)
identify.wait_for_server()

greet = SimpleActionClient("greet", GreetAction)
greet.wait_for_server()

get_name = SimpleActionClient("get_name", GetNameAction)
get_name.wait_for_server()

learn_face = SimpleActionClient("learn_face", LearnFaceAction)
learn_face.wait_for_server()

get_command = SimpleActionClient("get_command", GetCommandAction)

# Wait to be greeted
wait_greet.send_goal_and_wait(WaitGreetGoal())

# Try and identify the person who greeted us
identify.send_goal_and_wait(IdentifyGoal())
identify_result = identify.get_result()

# Greet the person
greet.send_goal_and_wait(GreetGoal(name=identify_result.name))

if not identify_result.success:
    get_name.send_goal_and_wait(GetNameGoal())
    get_name_result = get_name.get_result()
    name = get_name_result.name
    learn_face.send_goal_and_wait(LearnFaceGoal(name))
else:
    name = identify_result.name

# Get a command from the person
get_command.send_goal_and_wait(GetCommandGoal(name))
command_result = get_command.get_result()
if not command_result.command:
    ## FINISH
    rospy.signal_shutdown()

# Execute the command
