#!/usr/bin/env python3
import rospy

rospy.init_node("better_qualification")

from qualification.msg import (
    WaitGreetAction,
    WaitGreetGoal,
    IdentifyAction,
    IdentifyGoal,
    GreetAction,
    GreetGoal,
    GetNameAction,
    GetNameGoal,
    LearnFaceAction,
    LearnFaceGoal,
    GetCommandAction,
    GetCommandGoal,
    GuideAction,
    GuideGoal,
    FindPersonAction,
    FindPersonGoal,
)

from pal_interaction_msgs.msg import TtsGoal, TtsAction


from actionlib import SimpleActionClient

current_location = "corridor"
current_person = "unknown"

tts = SimpleActionClient("/tts", TtsAction)
tts.wait_for_server()

wait_greet = SimpleActionClient("wait_greet", WaitGreetAction)
wait_greet.wait_for_server()

identify = SimpleActionClient("identify", IdentifyAction)
identify.wait_for_server()

greet = SimpleActionClient("greet", GreetAction)
greet.wait_for_server()

get_name = SimpleActionClient("get_name", GetNameAction)
get_name.wait_for_server()

learn_face = SimpleActionClient("learn_face", LearnFaceAction)
learn_face.wait_for_server()

get_command = SimpleActionClient("get_command", GetCommandAction)
get_command.wait_for_server()

guide = SimpleActionClient("guide", GuideAction)
guide.wait_for_server()

find_person = SimpleActionClient("find_person", FindPersonAction)
find_person.wait_for_server()


def after_guiding(to):
    global current_location
    current_location = to


commands = {
    "Please guide me to the lab.": (
        after_guiding,
        ["lab"],
        guide,
        GuideGoal,
        [
            current_person,
            current_location,
            "lab",
        ],
    ),
    "Please guide me to the kitchen.": (
        after_guiding,
        ["kitchen"],
        guide,
        GuideGoal,
        [
            current_person,
            current_location,
            "kitchen",
        ],
    ),
    "Could you please find Jared and ask if they need assistance.": (
        lambda: None,
        [],
        find_person,
        FindPersonGoal,
        ["jared", current_location],
    ),
}


# Wait to be greeted
wait_greet.send_goal_and_wait(WaitGreetGoal())

# Try and identify the person who greeted us
identify.send_goal_and_wait(IdentifyGoal())
identify_result = identify.get_result()

# Greet the person
greet.send_goal_and_wait(GreetGoal(name=identify_result.name))

if not identify_result.success:
    get_name.send_goal_and_wait(GetNameGoal())
    get_name_result = get_name.get_result()
    name = get_name_result.name
    learn_face.send_goal_and_wait(LearnFaceGoal(name))
else:
    name = identify_result.name

current_person = name

while not rospy.is_shutdown():

    # Get a command from the person
    get_command.send_goal_and_wait(GetCommandGoal(name))
    command_result = get_command.get_result()
    if not command_result.command:
        ## FINISH
        rospy.signal_shutdown(0)

    # Execute the command
    command = command_result.command
    post_cmd, post_cmd_args, action, goal, goal_args = commands[command]
    goal = goal(*goal_args)
    action.send_goal_and_wait(goal)
    post_cmd(*post_cmd_args)
