# Path to input text files
string[] txt_paths

# Path to corresponding index files
string[] index_paths

# Sentence to query index with
string query_sentence

# Number of nearest sentences to return
uint8 k

# Number of vectors per txt file -- used to speed
# up lookup.
int32[] vecs_per_txt_file

---
# Nearest sentence
string[] closest_sentences

# Cosine similarity of distances
float32[] cosine_similarities

