#!/usr/bin/env python3
import rospy
import requests
from lasr_rasa.srv import Rasa, RasaResponse
import sys

class RasaWrapper:
    def __init__(self, api_url):
        self.api = api_url

    def __call__(self, req):
        response = RasaResponse()
        resp = requests.post(self.api, json={"text": req.text})
        if resp.status_code == 200:
            response.json_response = str(resp.json())
            response.success = True
        else:
            response.success = False
        return response


if __name__ == "__main__":
    if len(sys.argv) > 1:
        try:
            PORT = int(sys.argv[1])
        except ValueError:
            print("Usage: rosrun lasr_rasa service [PORT]")
            sys.exit()
    else:
        PORT = 5005

    rospy.init_node("lasr_rasa")
    rasa = RasaWrapper(f"http://localhost:{PORT}/model/parse")
    rospy.Service("/lasr_rasa/parse", Rasa, rasa)
    rospy.spin()
