restaurant:
  ros__parameters:
    bar_pose:
      position:
        x: 2.3735053539276123
        y: -0.11031855642795563
        z: -0.001434326171875

      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1
    barman_pose:
      position: 
        x: 2.051384687423706
        y: -0.7127782106399536
        z: -0.001434326171875

      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1
    table_pose:
      position: 
        x: 1.1867495775222778
        y: -0.8909675478935242
        z: -0.001434326171875

      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    guest_pose:
      position: 
        x: 1.0789965391159058
        y: 0.22096098959445953
        z: -0.0013427734375
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    ordered_food: ["pizza", "soda"]
    wait_duration: 10
    priors:
      items: ["cola", "water", "juice", "coffee", "tea", "sandwich", "cookie", "chips"]
