from .speech_recovery import SpeechRecovery
from .get_name_and_drink import GetNameAndDrink
from .get_attributes import GetGuestAttributes
from .introduce import Introduce
from .find_and_look_at import FindAndLookAt
from .receptionist_learn_face import ReceptionistLearnFaces
from .detect_faces import DetectFaces
from .get_name_or_drink import GetNameOrDrink
from .handle_guest import HandleGuest
from .pointcloud_sweep import PointCloudSweep
from .run_and_process_detections import RunAndProcessDetections
from .recognise_people import RecognisePeople
from .seat_guest import SeatGuest
from .check_sofa import CheckSofa
from .introduce_and_seat_guest import IntroduceAndSeatGuest
