#!/usr/bin/env python3

import rospy
import rospkg
import lasr_object_detection_yolov8 as yolo

from sensor_msgs.msg import Image
from lasr_object_detection_yolo.srv import YoloDetection, YoloDetectionRequest, YoloDetectionResponse

# Put ourselves in the model folder
import os
import rospkg
rp = rospkg.RosPack()
package_path = rp.get_path('lasr_object_detection_yolov8')
os.chdir(os.path.abspath(os.path.join(package_path, 'models')))

# Initialise rospy
rospy.init_node('yolov8_service')

# Determine variables
DEBUG = rospy.get_param('~debug', False)
PRELOAD = rospy.get_param('~preload', [])

for model in PRELOAD:
    yolo.load_model(model)

# Prepare publisher
debug_publisher = None
if DEBUG:
    debug_publisher = rospy.Publisher('/yolov8/debug', Image, queue_size=1)

def detect(request: YoloDetectionRequest) -> YoloDetectionResponse:
    '''
    Hand off detection request to yolo library
    '''
    return yolo.detect(request, debug_publisher)

rospy.Service('/yolov8/detect', YoloDetection, detect)
rospy.loginfo('YOLOv8 service started')
rospy.spin()
