#!/usr/bin/env python3

import rospy
import os
import rospkg
from lasr_vision_msgs.srv import CheckKnownPeopleRequest, CheckKnownPeopleResponse, CheckKnownPeople

DATASET_ROOT = os.path.join(
    rospkg.RosPack().get_path("lasr_vision_deepface"), "datasets"
)

rospy.init_node("check_known_people_service")

def check_known_people(request : CheckKnownPeopleRequest) -> CheckKnownPeopleResponse:
    dataset_path = os.path.join(DATASET_ROOT, request.task_name)
    known_people_names = [
        f
        for f in os.listdir(dataset_path)
        if os.path.isdir(os.path.join(dataset_path, f))
    ]
    rospy.set_param("/known_people", known_people_names)
    return CheckKnownPeopleResponse(known_people_names)

rospy.Service("/check_known_people", CheckKnownPeople, check_known_people)
rospy.loginfo("Check known people service started")
rospy.spin()