lasr_vision_open_vocabulary:
  ros__parameters:
    model: 'grounding_dino'
    model_device: 'cuda'
    grounding_dino_weights: ''
    yoloworld_weights: 'yolov8s-world.pt'
    use_sam: false
    sam_encoder_path: ''
    sam_decoder_path: ''
