name: Continuous

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'main'
jobs:
  QC:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository and Submodules
      uses: actions/checkout@v4
    - name: Quality Control
      uses: "./.github/workflows/qc"
  Documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository and Submodules
      uses: actions/checkout@v4
    - name: Build & Deploy Documentation
      uses: "./.github/workflows/docs"
