name: Pull Request

on:
  pull_request:
    branches:
    - '*'
jobs:
  QC:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Quality Control
      uses: "./.github/workflows/qc"