doing_laundry:
  ros__parameters:
    laundry_area:
      pose:
        position:
          x: -14.250353
          y: 20.145838
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0