receptionist_node: # Must match node (parameters are related to nodes)
  ros__parameters:    
    priors:
      names:
        - Adel
        - Angel
        - Axel
        - Charlie
        - Jane
        - Jules
        - Morgan
        - Paris
        - Robin
        - Simone
      drinks:
        - cola
        - iced tea
        - juice pack
        - milk
        - orange juice
        - red wine
        - tropical juice